@startuml Recieve_PM_data_hybrid_mw_structure
title "Recieve historical performance data of hybrid mw structure"

actor Requester
participant MycomButler
participant MWDI

Requester -> MycomButler: Request: GET /v1/provide-historical-pm-data-of-device/{mountName}/hybrid-mw-structure/{logicalTerminationPoint}/{layerProtocol}
activate MycomButler

MycomButler -> MWDI: Request: GET /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/hybrid-mw-structure-2-0:hybrid-mw-structure-pac/hybrid-mw-structure-capability
activate MWDI
MWDI -> MycomButler: Response: HybridMWStructureCapabilities
deactivate MWDI

MycomButler -> MWDI: Request: GET /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/hybrid-mw-structure-2-0:hybrid-mw-structure-pac/hybrid-mw-structure-configuration
activate MWDI
MWDI -> MycomButler: Response: HybridMWStructureConfiguration
deactivate MWDI

MycomButler -> MWDI: Request: GET /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/hybrid-mw-structure-2-0:hybrid-mw-structure-pac/hybrid-mw-structure-historical-performances
activate MWDI
MWDI -> MycomButler: Response: HybridMWStructureHistoricalPerformances
deactivate MWDI

MycomButler -> Requester: Response: HybridMWStructurePerformanceData

deactivate MycomButler

@enduml
