@startuml Recieve_PM_data_air_interface
title "Recieve historical performance data of air interface"

actor Requester
participant MycomButler
participant MWDI

Requester -> MycomButler: Request: GET /provide-historical-performance-data/{mount-name}/air-interface/{logical-termination-point}/{layer-protocol}

activate MycomButler
MycomButler -> MWDI: Request: GET /core-model-1-4:network-control-domain=cache/control-construct={mount-name}/logical-termination-point={uuid}/layer-protocol={local-id}/air-interface-2-0:air-interface-pac

activate MWDI
MWDI -> MycomButler: Response: PMDataAirInterface

deactivate MWDI
MycomButler -> Requester: Response: PerformanceData

deactivate MycomButler

@enduml
