@startuml Recieve_PM_data_ethernet_container
title "Recieve historical performance data of ethernet container"

actor Requester
participant MycomButler
participant MWDI

Requester -> MycomButler: Request: GET /v1/provide-historical-pm-data-of-device/{mountName}/ethernet-container/{logicalTerminationPoint}/{layerProtocol}
activate MycomButler

MycomButler -> MWDI: Request: GET /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/ethernet-container-2-0:ethernet-container-pac/ethernet-container-capability
activate MWDI
MWDI -> MycomButler: Response: EthernetContainerCapabilities
deactivate MWDI

MycomButler -> MWDI: Request: GET /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/ethernet-container-2-0:ethernet-container-pac/ethernet-container-configuration
activate MWDI
MWDI -> MycomButler: Response: EthernetContainerConfiguration
deactivate MWDI

MycomButler -> MWDI: Request: GET /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/ethernet-container-2-0:ethernet-container-pac/ethernet-container-historical-performances
activate MWDI
MWDI -> MycomButler: Response: EthernetContainerHistoricalPerformances
deactivate MWDI

MycomButler -> Requester: Response: EthernetContainerPerformanceData

deactivate MycomButler

@enduml
