@startuml Recieve_PM_data_wire_interface
title "Recieve historical performance data of wire interface"

actor Requester
participant MycomButler
participant MWDI

Requester -> MycomButler: Request: GET /v1/provide-historical-pm-data-of-device/{mountName}/wire-interface/{logicalTerminationPoint}/{layerProtocol}

activate MycomButler

MycomButler -> MWDI: Request: GET /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/pure-ethernet-structure-2-0:pure-ethernet-structure-pac/pure-ethernet-structure-capability
activate MWDI
MWDI -> MycomButler: Response: WireInterfaceCapabilities
deactivate MWDI

MycomButler -> MWDI: Request: GET /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/pure-ethernet-structure-2-0:pure-ethernet-structure-pac/pure-ethernet-structure-configuration
activate MWDI
MWDI -> MycomButler: Response: WireInterfaceConfiguration
deactivate MWDI

MycomButler -> MWDI: Request: GET /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/pure-ethernet-structure-2-0:pure-ethernet-structure-pac/pure-ethernet-structure-configuration
activate MWDI
MWDI -> MycomButler: Response: WireInterfaceHistoricalPerformances
deactivate MWDI



MycomButler -> Requester: Response: WireInterfacePerformanceData

deactivate MycomButler
@enduml
