@startuml Recieve_PM_data_pure_ethernet_structure
title "Recieve historical performance data of pure ethernet structure"

actor Requester
participant MycomButler
participant MWDI

Requester -> MycomButler: Request: GET /v1/provide-historical-pm-data-of-device/{mountName}/pure-ethernet-structure/{logicalTerminationPoint}/{layerProtocol}
activate MycomButler

MycomButler -> MWDI: Request: GET /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/pure-ethernet-structure-2-0:pure-ethernet-structure-pac/pure-ethernet-structure-capability
activate MWDI
MWDI -> MycomButler: Response: PureEthernetStructureCapabilities
deactivate MWDI

MycomButler -> MWDI: Request: GET /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/pure-ethernet-structure-2-0:pure-ethernet-structure-pac/pure-ethernet-structure-configuration
activate MWDI
MWDI -> MycomButler: Response: PureEthernetStructureConfiguration
deactivate MWDI

MycomButler -> MWDI: Request: GET /core-model-1-4:network-control-domain=cache/control-construct={mountName}/logical-termination-point={uuid}/layer-protocol={localId}/pure-ethernet-structure-2-0:pure-ethernet-structure-pac/pure-ethernet-structure-configuration
activate MWDI
MWDI -> MycomButler: Response: PureEthernetStructureHistoricalPerformances
deactivate MWDI

MycomButler -> Requester: Response: PureEthernetStructurePerformanceData

deactivate MycomButler

@enduml
