@startuml Recieve_Device_Data
title Recieve historical performance data

actor Requester
participant MycomButler
participant MWDI

Requester -> MycomButler: Request: GET /provide-historcial-performance-data/{mountName}

activate MycomButler
MycomButler -> MWDI: Request: GET /core-model-1-4:network-control-domain=cache/control-construct={mountName}?fields=logical-termination-point

activate MWDI
MWDI -> MycomButler: Response: DeviceData

deactivate MWDI
MycomButler -> Requester: Response: PerformanceData

deactivate MycomButler

@enduml
