@startuml Mycom_Export
title Provide historical PM Data of device

actor Requester
participant MycomButler
participant MWDI

Requester -> MycomButler: Request: POST /v1/provide-historical-pm-data-of-device?fields
activate MycomButler
    MycomButler -> MWDI: Request: POST /v1/provide-list-of-device-interfaces
    MWDI --> MycomButler: Response: logical-termination-point-list(uuid, localId, layer-protocol-name)
    loop for each [localId] depending on layer-protocol-name
        alt layer-protocol-name equals air-interface-2-0
            MycomButler -> MWDI: Request:GET /core-model-1-4:network-control-domain=cache/control-construct={deviceId}/logical-termination-point={uuid}?fields=uuid;ltp-augment-1-0:ltp-augment-pac(external-label);layer-protocol(local-id;layer-protocol-name;air-interface-2-0:air-interface-pac)
            MWDI --> MycomButler: Response: Logical-Termination-Point Air-Interface
        else layer-protocol-name equals layer-protocol-name wire-interface-2-0
                        MycomButler -> MWDI: Request:GET /core-model-1-4:network-control-domain=cache/control-construct={deviceId}/logical-termination-point={uuid}?fields=uuid;ltp-augment-1-0:ltp-augment-pac(external-label);layer-protocol(local-id;layer-protocol-name;wire-interface-2-0:wire-interface-pac)
                        MWDI --> MycomButler: Response: Logical-Termination-Point Wire-Interface
        else layer-protocol-name equals layer-protocol-name hybrid-mw-structure-2-0
            MycomButler -> MWDI: Request:GET /core-model-1-4:network-control-domain=cache/control-construct={deviceId}/logical-termination-point={uuid}?fields=uuid;ltp-augment-1-0:ltp-augment-pac(external-label);layer-protocol(local-id;layer-protocol-name;hybrid-mw-structure-2-0:hybrid-mw-structure-pac)
            MWDI --> MycomButler: Response: Logical-Termination-Point Hybrid-MW-Structure
        else layer-protocol-name equals layer-protocol-name pure-ethernet-structure-2-0
            MycomButler -> MWDI: Request:GET /core-model-1-4:network-control-domain=cache/control-construct={deviceId}/logical-termination-point={uuid}?fields=uuid;ltp-augment-1-0:ltp-augment-pac(external-label);layer-protocol(pure-ethernet-structure-2-0:pure-ethernet-structure-pac)
            MWDI --> MycomButler: Response: Logical-Termination-Point Pure-Ethernet-Structure
        else layer-protocol-name equals layer-protocol-name ethernet-container-2-0
            MycomButler -> MWDI: Request:GET /core-model-1-4:network-control-domain=cache/control-construct={deviceId}/logical-termination-point={uuid}?fields=uuid;ltp-augment-1-0:ltp-augment-pac(external-label);layer-protocol(local-id;layer-protocol-name;ethernet-container-2-0:ethernet-container-pac)
            MWDI --> MycomButler: Response: Logical-Termination-Point Ethernet-Container
        end
    end
MycomButler --> Requester: HistoricalPMData(List<AirInterface>,List<AirInterface>,List<EthernetContainer>,List<HybridMW>,List<PureEthernetStructure>,List<WireInterface>)
deactivate MycomButler
@enduml
